Repository 2nnerPeace/The-Moon-Ha-React, pull requests merged in 2024-09, with the labels that each got.

#3 [KAN-60] [COMMON] 공통 컴포넌트 Header, Siderbar 구현 및 colors.xml, font.css 정리
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/Router.js
  src/assets/font/Happiness-Sans-Bold.woff
  src/assets/font/Happiness-Sans-Bold.woff2
  src/assets/font/Happiness-Sans-Regular.woff
  src/assets/font/Happiness-Sans-Regular.woff2
  src/assets/font/Happiness-Sans-Title.woff
  src/assets/font/Happiness-Sans-Title.woff2
  src/assets/font/HappinessSansVF.woff2
  src/assets/images/analysticIcon.svg
  src/assets/images/craftIcon.svg
  src/assets/images/lessonIcon.svg
  src/assets/images/logo.svg
  src/assets/images/shortFormIcon.svg
  src/assets/images/studioIcon.svg
  src/components/Default/styled.js
  src/components/Header/index.jsx
  src/components/Header/styled.js
  src/components/Sidebar/index.jsx
  src/components/Sidebar/styled.js
  src/components/SidebarButton/index.jsx
  src/components/SidebarButton/styled.js
  src/index.js
  src/logo.svg
  src/pages/Craft/index.jsx
  src/pages/Craft/styled.js
  src/pages/Lesson/index.jsx
  src/pages/Lesson/styled.js
  src/pages/Main/index.jsx
  src/pages/Main/styled.js
  src/pages/Prologue/index.jsx
  src/pages/Prologue/styled.js
  src/pages/ShortForm/index.jsx
  src/pages/ShortForm/styled.js
  src/pages/Studio/index.jsx
  src/pages/Studio/styled.js
  src/pages/Suggestion/index.jsx
  src/pages/Suggestion/styled.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/colors.js
  src/styles/font.css
  src/styles/index.css
Labels: Feat

#13 [CRAFT] [KAN-16] 영상 플레이어 추가해서 프롤로그 상세보기 구현하기
  package-lock.json
  package.json
  src/apis/Craft/index.js
  src/components/Player/index.jsx
  src/components/Player/syteld.js
  src/components/PrologueDetail/index.jsx
  src/components/Table/index.jsx
  src/components/Table/styled.js
Labels: Feat

#21 [COMMON] [KAN-60] CI/CD 테스트 및 .env 파일로 도메인 로컬, 배포 구분
  .gitignore
  src/apis/index.js
Labels: Feat, Chore

#23 [LESSON] [KAN-14] 숏폼 월별 조회 페이지 구현
  package-lock.json
  package.json
  src/Router.js
  src/apis/Lesson/index.js
  src/assets/images/arrowLeft.svg
  src/assets/images/arrowRight.svg
  src/components/Button/index.jsx
  src/components/Button/styled.js
  src/components/CalendarHeader/index.jsx
  src/components/CalendarHeader/styled.js
  src/components/Default/styled.js
  src/components/DropdownWithGroup/index.jsx
  src/components/DropdownWithGroup/styled.js
  src/components/Header/styled.js
  src/components/Player/index.jsx
  src/components/Player/syteld.js
  src/components/ShortFormList/index.jsx
  src/components/ShortFormList/styled.js
  src/components/ShortFormRegister/index.jsx
  src/components/Sidebar/styled.js
  src/components/TabMenu/index.jsx
  src/layout/index.jsx
  src/layout/styled.js
  src/pages/ShortForm/index.jsx
  src/styles/colors.js
Labels: Feat

#25 [AUTH] [KAN-11] 간단 로그아웃 구현
  src/apis/Auth/index.js
  src/components/Header/index.jsx
Labels: Feat

#20 [LIVE] [KAN-58] 실시간 강좌 열기 관리자 화면 구현
  package-lock.json
  package.json
  src/Router.js
  src/components/LiveBroadcastComponent/index.jsx
  src/components/LiveBroadcastComponent/styled.js
  src/components/LiveStartComponent/index.jsx
  src/components/LiveStartComponent/styled.js
  src/components/Sidebar/index.jsx
  src/pages/LiveBroadcastPage/index.jsx
  src/pages/LiveBroadcastPage/styled.js
  src/pages/LiveStartPage/index.jsx
  src/pages/LiveStartPage/styled.js
  src/pages/Studio/index.jsx
  src/pages/Studio/styled.js
Labels: Feat

#27 [AUTH] [KAN-11] 로그인 새로고침해도 유지, 로그아웃 cursor pointer로 변경
  package-lock.json
  package.json
  src/components/Button/styled.js
  src/recoil/index.js
Labels: Feat

#30 [LIVE] [KAN-53] 실시간 강좌 열기 구현
  package-lock.json
  package.json
  public/index.html
  src/apis/Lesson/index.js
  src/apis/Live/index.js
  src/components/LiveBroadcastComponent/index.jsx
  src/components/LiveBroadcastComponent/styled.js
  src/components/LiveStartComponent/index.jsx
  src/components/LiveStartComponent/styled.js
Labels: Fix, Feat, Refactor

#31 [LESSON] [KAN-13][KAN-16] 강좌 등록 수정 및 S3 Presigned URL 기능 추가
  src/apis/Craft/index.js
  src/apis/S3/index.js
  src/components/Dropdown/index.jsx
  src/components/DropdownWithGroup/index.jsx
  src/components/LessonDetail/index.jsx
  src/components/LessonList/styled.js
  src/components/LessonRegister/index.jsx
  src/components/LessonRegister/styled.js
  src/components/PrologueList/index.jsx
  src/components/PrologueRegister/index.jsx
  src/components/Table/index.jsx
  src/components/Table/styled.js
  src/util/index.js
Labels: Feat, Refactor

#34 [ADMIN] [KAN-13][KAN-60] 비디오 미리보기 재생 및 UI 수정
  src/components/LessonList/styled.js
  src/components/LessonRegister/index.jsx
  src/components/Player/index.jsx
  src/components/PrologueRegister/index.jsx
  src/components/ShortFormList/styled.js
  src/components/ShortFormRegister/index.jsx
  src/components/Upload/index.jsx
  src/components/Upload/styled.js
Labels: Feat, Refactor, Style

#36 [ADMIN] [KAN-13][KAN-14][KAN-16] 전체적 UI 수정
  src/apis/index.js
  src/assets/images/contentDeleteBtnIcon.svg
  src/components/Button/styled.js
  src/components/DatePicker/index.jsx
  src/components/DatePicker/styled.js
  src/components/Dropdown/index.jsx
  src/components/Dropdown/styled.js
  src/components/DropdownWithGroup/index.jsx
  src/components/DropdownWithGroup/styled.js
  src/components/Header/index.jsx
  src/components/LessonDetail/index.jsx
  src/components/LessonDetail/styled.js
  src/components/LessonRegister/index.jsx
  src/components/LessonRegister/styled.js
  src/components/Modal/styled.js
  src/components/Player/syteld.js
  src/components/PrologueDetail/index.jsx
  src/components/PrologueDetail/styled.js
  src/components/PrologueList/index.jsx
  src/components/PrologueList/styled.js
  src/components/PrologueRegister/index.jsx
  src/components/PrologueRegister/styled.js
  src/components/ShortFormList/index.jsx
  src/components/ShortFormList/styled.js
  src/components/ShortFormRegister/index.jsx
  src/components/ShortFormRegister/styled.js
  src/components/Table/index.jsx
  src/components/Table/styled.js
  src/components/TimePicker/index.jsx
  src/components/TimePicker/styled.js
  src/components/Upload/index.jsx
  src/components/Upload/styled.js
  src/components/WeekPicker/index.jsx
  src/components/WeekPicker/styled.js
  src/layout/styled.js
  src/pages/LessonRegister/styled.js
  src/pages/Prologue/styled.js
  src/pages/ShortFormRegister/styled.js
Labels: Feat, Design

#37 [COMMON] [KAN-60] 통신 timeout 늘리기
  src/apis/index.js
Labels: Refactor, Chore

#39 [KAN-53] Fix: 실시간 강좌 종료 시점 수정
  src/components/LiveBroadcastComponent/index.jsx
Labels: Fix

#42 [COMMON] [KAN-44] 주석 추가
  src/apis/Live/index.js
  src/components/LiveBroadcastComponent/index.jsx
  src/components/LiveStartComponent/index.jsx
  src/pages/LiveBroadcastPage/index.jsx
  src/pages/LiveStartPage/index.jsx
Labels: Style
